// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[id]/trading.tsx";
import * as $1 from "./routes/api/auth.ts";
import * as $2 from "./routes/api/graphql.ts";
import * as $3 from "./routes/graphql/schema.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/joinclass.tsx";
import * as $6 from "./routes/models/company.ts";
import * as $7 from "./routes/models/newsStory.ts";
import * as $8 from "./routes/models/user.ts";
import * as $9 from "./routes/signin.tsx";
import * as $$0 from "./islands/Homepage.tsx";
import * as $$1 from "./islands/JoinClassPage.tsx";
import * as $$2 from "./islands/Signin.tsx";
import * as $$3 from "./islands/Tradepage.tsx";

const manifest = {
  routes: {
    "./routes/[id]/trading.tsx": $0,
    "./routes/api/auth.ts": $1,
    "./routes/api/graphql.ts": $2,
    "./routes/graphql/schema.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/joinclass.tsx": $5,
    "./routes/models/company.ts": $6,
    "./routes/models/newsStory.ts": $7,
    "./routes/models/user.ts": $8,
    "./routes/signin.tsx": $9,
  },
  islands: {
    "./islands/Homepage.tsx": $$0,
    "./islands/JoinClassPage.tsx": $$1,
    "./islands/Signin.tsx": $$2,
    "./islands/Tradepage.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
